name: C/C++ CI

on:
  push:
    branches: [ master, v1 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make image_unittest
      run: make image_unittest
      working-directory: graphics
